# Generated by Django 2.2.1 on 2020-05-26 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dipapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 26, 22, 42, 54, 719642)),
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 26, 22, 42, 54, 719642)),
        ),
    ]
